version: "2.2"
services:
  mysql:
    image: mysql:5.7
    container_name: "dbc02"
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Welcome"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "naresh"
      MYSQL_PASSWORD: "Welcome"
    healthcheck:
      test: "/usr/bin/mysql --user=naresh --password=Welcome --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 1s
      retries: 5
    volumes:
      - my-datavolume:/var/lib/mysql
    networks:
      - db-nw
volumes:
  my-datavolume:
networks:
  db-nw: